### PR TITLE
Added support for installing via UPM.

### PR DESCRIPTION
**Pull request by neogeek**
This PR adds support for installing this project via UPM (Unity Package Manager).

Read more at:
1. https://docs.unity3d.com/Manual/Packages.html
1. https://neogeek.dev/creating-custom-packages-for-unity-2018.3/

The changes made in this PR:
1. Added an assembly reference file in the main project.
1. Added an assembly reference in the test folder to limit access to the editor only.
1. Added a package.json file with information about the project. This file is used by Unity to identify the project as a UPM repo.
1. Changed access modifiers from internal to public to allow access to the main project files from the test folder.

To deploy changes from master to a branch that can be installed by UPM, push the latest changes to a subtree branch named `upm` using the following command:

```bash
$ git subtree push --prefix Assets origin upm
```

Once the changes are pushed, the project can be installed by adding https://github.com/GlitchEnzo/NuGetForUnity.git#upm via the UPM panel by selecting **Add packages from git URL.**

You can also deploy versions that can be installed via UPM by creating a new tag/release from the `upm` branch. Once released, versions can then be installed by adding the tag to the end of the URL in place of `upm`.

https://github.com/GlitchEnzo/NuGetForUnity.git#upm
https://github.com/GlitchEnzo/NuGetForUnity.git#v1.0.0

Let me know if you have any questions about this PR.

### CODE REVIEW

**Comment by jwittner** [comment]
Awesome! I'll take some time next week to dig through this and test it out. Thanks for the cool contribution!

**Comment by fpainchaud** [comment]
Hey Scott "neogeek". Since NuGetForUnity is an Editor tool, "NuGetForUnity.asmdef" should be under "NuGet/Editor/" with its "includePlatforms" set to "Editor" only. Otherwise, building the project gives errors when Unity also tries to build the package. FYI, I'm using Unity 2020.1.6f1.

**Comment by neogeek** [comment]
@fpainchaud Good catch. I set the tests to run in the editor only but forgot to do that to the project's main assembly reference. I'll push a fix for that shortly.

**Comment by neogeek** [comment]
Pushed a fix and tested by building a test project locally. Thanks again for the catch @fpainchaud!

**Comment by jwittner** [comment]
Unfortunately I was unable to get to this this week, however I've set aside explicit calendar time to check this out next week. Sorry for the delay!

**Review by jwittner — CHANGES_REQUESTED** [review]
Couple logistical things, but otherwise a great change!

**Comment by JoC0de** [comment]
Implement it in #480.
@neogeek Thanks for the inspiration.

**Pull request closed without merging**
