### PR TITLE
Handle Directory Entries in nupkg Files

### PR DESCRIPTION
**Pull request by DWishR**
Note that this includes PR #385.

Addresses issue #375.

Improvements:
- Detects if the entry in the zip archive is a directory and handles this correctly.

Tested against `Google.Protobuf` and `Microsoft.Extensions.Primitives` v2.0.0 (note latest Primitives doesn't have this issue)

### CODE REVIEW

**Comment by jwittner** [comment]
Thanks a ton for the contribution!!! Very strange packaging there. We'll wait to get #385 in first.

**Comment by DWishR** [comment]
Here's a unity package, for anyone else wanting to test. Unzip and then open the .unitypackage with your Unity project open.
[NugetForUnity.zip](https://github.com/GlitchEnzo/NuGetForUnity/files/6320847/NugetForUnity.zip)

**Comment by jwittner** [comment]
I've merged #385. I wish the diff for this PR would update. =(

**Comment by jwittner** [comment]
Hooray - you're merge of master updated the diff! =)

**Comment by DWishR** [comment]
Happy to help

**Pull request merged**
