### PR TITLE
Deleting unnecessary folders after update packages.config from git.

### PR DESCRIPTION
**Pull request by vandelpal**
Description of the problem that is solved:
When one developer uninstall any package and commit it. The folder remove on this developer pc, but other developer pull this changes, Assets/Packages folder in ignore, open Unity and automatically start restore packages. Folder still exist because there is no code for check this.

### CODE REVIEW

**Comment by jwittner** [comment]
The issue I have with this operation is that it assumes NuGet owns everything in the repository. We often find it useful to embed an installed package into our source tree and remove it from the packages config - this change would prevent that work flow.

I'd be open to adding a 'Clean' option via another button or something similar to invoke the wipe then Restore. For those of us using the above workflow we'll have to use 'git' externally to restore that missing content, but at least the normal flow wouldn't break.

Open to other ideas as well, of course. =)

Visual Studio doesn't have this problem, because it uses a reference in the project to link to the package contents. We don't have that option in Unity right now. =(

**Comment by vandelpal** [comment]
Nuget owns everything only in the Asset/Packages ignored folder, why not?  You can embed some package in other folder for source tree.

**Comment by vandelpal** [comment]
In Unity 2018 the Packages folder is now used for its own purposes.  
From upgrade Guide:
"If your project uses Nuget (or any external package manager) in a way that makes it use the Packages directory, its configuration should be changed to use a different directory. This is recommended to eliminate the small chance that a package be picked up by the Unity Package Manager, which could result in hard-to-debug issues like compilation errors or import errors."

Therefore, I propose to change the folder and give it completely under the control of the Nuget.

**Comment by jwittner** [comment]
The Unity Package Manager 'Packages' folder resides alongside the Assets folder, where as the NuGetForUnity 'Packages' folder is embedded inside the Assets folder. See #133 and #165 for references to this. =)

Seems reasonable to move the contents out of the packages folder. I'll test your PR soon and give it a functionality review.

**Pull request merged**
