### PR TITLE
fallback method for GetUpdates for use with Visual Studio Team Services, which doesn't support this API

### LINKED ISSUE #101: nuget/v2/GetUpdates() web requests fail so the updates window doesn't work
I'm seeing some errors in web request with GetUpdates(). This occurs when I attempt to install a package from a VSTS feed that has a dependency on another package. It seems to be preventing these dependencies from being automatically installed.

I'll need to do some further investigation to see if this is an incompatibility specific to the VSTS feed or something related to way NuGetForUnity if making its requests.

For now I'm just posting this error message so others are aware of it.

Here is an example of the sort of errors I'm receiving:
``Unable to retrieve package list from https://myteam.pkgs.visualstudio.com/_packaging/myteam/nuget/v2/GetUpdates()?packageIds='Performance'&versions='1.0.2835'&includePrerelease=false&includeAllVersions=false&targetFrameworks=''&versionConstraints=''
System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at NugetForUnity.NugetHelper.RequestUrl (System.String url, System.String password, System.Nullable`1[T] timeOut) [0x0007f] in D:\s\NuGetForUnity\Assets\NuGet\Editor\NugetHelper.cs:1144 
  at NugetForUnity.NugetPackageSource.GetPackagesFromUrl (System.String url, System.String password) [0x0005f] in D:\s\NuGetForUnity\Assets\NuGet\Editor\NugetPackageSource.cs:333 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetPackageSource:GetPackagesFromUrl(String, String) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetPackageSource.cs:345)
NugetForUnity.NugetPackageSource:GetUpdates(IEnumerable`1, Boolean, Boolean, String, String) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetPackageSource.cs:432)
NugetForUnity.NugetHelper:GetUpdates(List`1, Boolean, Boolean, String, String) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetHelper.cs:813)
NugetForUnity.NugetWindow:UpdateUpdatePackages() (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:338)
NugetForUnity.NugetWindow:DrawPackage(NugetPackage) (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:820)
NugetForUnity.NugetWindow:DrawOnline() (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:513)
NugetForUnity.NugetWindow:OnGUI() (at D:/s/NuGetForUnity/Assets/NuGet/Editor/NugetWindow.cs:378)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)``

### PR DESCRIPTION
**Pull request by ForrestTrepte**
This change fixes #101.

### CODE REVIEW

**Comment by ForrestTrepte** [comment]
@jwittner I ended up leaving this as a fallback path because, in a test project using several nuget.org packages, the GetUpdates call is an order of magnitude faster than the alternative of getting each package individually.

**Comment by jwittner** [comment]
Checking this locally!

**Comment by jwittner** [comment]
The updates window does populate, but when I try to install the updates from it I get this error:
```
Unable to install package <redacted>
System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at NugetForUnity.NugetHelper.RequestUrl (System.String url, System.String password, System.Nullable`1[T] timeOut) [0x0008b] in C:\Users\jowitt\Source\NuGetForUnity\Assets\NuGet\Editor\NugetHelper.cs:1169 
  at NugetForUnity.NugetHelper.Install (NugetForUnity.NugetPackage package, System.Boolean refreshAssets) [0x00307] in C:\Users\jowitt\Source\NuGetForUnity\Assets\NuGet\Editor\NugetHelper.cs:1077 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetHelper:Install(NugetPackage, Boolean) (at Assets/NuGet/Editor/NugetHelper.cs:1119)
NugetForUnity.NugetHelper:InstallIdentifier(NugetPackageIdentifier) (at Assets/NuGet/Editor/NugetHelper.cs:965)
NugetForUnity.NugetHelper:Restore() (at Assets/NuGet/Editor/NugetHelper.cs:1202)
NugetForUnity.NugetHelper:.cctor() (at Assets/NuGet/Editor/NugetHelper.cs:113)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()
```

It then hangs for quite some time "Restoring", but eventually fails with a timeout:
```
Unable to install package <redacted>
System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at NugetForUnity.NugetHelper.RequestUrl (System.String url, System.String password, System.Nullable`1[T] timeOut) [0x0008b] in C:\Users\jowitt\Source\NuGetForUnity\Assets\NuGet\Editor\NugetHelper.cs:1169 
  at NugetForUnity.NugetHelper.Install (NugetForUnity.NugetPackage package, System.Boolean refreshAssets) [0x00307] in C:\Users\jowitt\Source\NuGetForUnity\Assets\NuGet\Editor\NugetHelper.cs:1077 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetHelper:Install(NugetPackage, Boolean) (at Assets/NuGet/Editor/NugetHelper.cs:1119)
NugetForUnity.NugetHelper:InstallIdentifier(NugetPackageIdentifier) (at Assets/NuGet/Editor/NugetHelper.cs:965)
NugetForUnity.NugetHelper:Restore() (at Assets/NuGet/Editor/NugetHelper.cs:1202)
NugetForUnity.NugetHelper:.cctor() (at Assets/NuGet/Editor/NugetHelper.cs:113)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

```

**Comment by jwittner** [comment]
@GlitchEnzo  - Are these build failures expected?

**Comment by GlitchEnzo** [comment]
Yeah those failures are expected. Sorry about the noise.

I'm hoping to have the build server fixed up soon. (I've been having issues with it creating the .unitypackage file, so I might just have it build the DLL and be done with it.)

**Comment by jwittner** [comment]
Cool! If you're using PowerShell you might checkout UnitySetup - it's the tooling for this kind of scenario we've been putting together. It was designed for just these kinds of cases.

**UnitySetup** - [GitHub.](https://github.com/Microsoft/unitysetup.powershell) [PowerShell Gallery.](https://www.powershellgallery.com/packages/UnitySetup)

**Comment by ForrestTrepte** [comment]
@jwittner: I was seeing request timed out errors a little bit ago (with and without my change) and then recently it started working again. Perhaps a hiccup with our VSTS package feed?

**Comment by jwittner** [comment]
Ok, I'll check it out again right now.

**Comment by jwittner** [comment]
Still fails in the same way. Installing the old version works fine, but when I try to update from the Updates tab it hangs indefinitely and then times out.

**Comment by ForrestTrepte** [comment]
@jwittner I entered the problem that you observed as #134, which reproduced for me without this GetUpdates change. I have a fix for it in #135. If you would like, you could merge both #132 and #135 to test and review them simultaneously and I expect that the problem you were seeing will be fixed.

**Comment by jwittner** [comment]
Checking again now that #134 is resolved.

**Pull request merged**
