### PR TITLE
Changed NuspecEditor to be EditorWindow

### LINKED ISSUE #116: Change the .nuspec editor to no longer be a custom Inspector
Currently the NuspecEditor injects itself as a custom inspector by taking over the generic "DefaultAsset".  This can be "unfriendly" to users who have their own custom editors for DefaultAssets.

This should probably be changed to be a context menu option that opens a separate editor window.

### PR DESCRIPTION
**Pull request by GlitchEnzo**
Previously it was a custom inspector that hijacked the DefaultAsset inspector. This doesn't play very nice in user projects that are also utilizing the DefaultAsset inspector.

Now, a separate editor window is opened via the context menu of a .nuspec file.  It can be docked and moved around separately from the inspector window.

Resolves #116

### CODE REVIEW

**Comment by GlitchEnzo** [comment]
Ignore the failing checks.  I created a Travis account and linked it to this repo, but I haven't configured it yet.  I didn't know it was going to inject failures into pull requests.

Sorry about that!

**Comment by jwittner** [comment]
Checking this locally.

**Comment by jwittner** [comment]
Worked great for me! The only UX thing I might change would be to auto open the Editor Window on creation of a new file.

**Comment by jwittner** [comment]
Also, super pumped to see you connect Travis CI! Baby steps. =)

**Pull request merged**
